version: 2
project_name: respex
builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    main: .
    ldflags:
      - -s -w -X respex/internal/cli.version={{.Version}}
archives:
  - formats: [binary]
    name_template: >-
      {{ .Binary }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}
      {{- if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: checksums.txt
